from __future__ import annotations

RUN_NEW = "NEW"
RUN_PLANNING = "PLANNING"
RUN_PLAN_READY = "PLAN_READY"
RUN_PLAN_REVIEW_REQUIRED = "PLAN_REVIEW_REQUIRED"
RUN_PLAN_REVISING = "PLAN_REVISING"
RUN_PLAN_APPROVED = "PLAN_APPROVED"
RUN_WORKING = "WORKING"
RUN_WORK_DONE = "WORK_DONE"
RUN_REVIEWING = "REVIEWING"
RUN_NEEDS_CHANGES = "NEEDS_CHANGES"
RUN_REVIEW_RETRYABLE = "REVIEW_RETRYABLE"
RUN_APPROVED = "APPROVED"
RUN_BLOCKED = "BLOCKED"
RUN_FAILED = "FAILED"

WORKER_ACTIVE = "ACTIVE"
WORKER_DONE = "DONE"

REVIEW_ATTEMPT_ACTIVE = "ACTIVE"
REVIEW_ATTEMPT_FAILED_RETRYABLE = "FAILED_RETRYABLE"

TERMINAL_RUN_STATUSES = frozenset({RUN_APPROVED, RUN_BLOCKED, RUN_FAILED})

RUN_STATUS_ORDER = {
    RUN_NEW: 0,
    RUN_PLANNING: 1,
    RUN_PLAN_READY: 2,
    RUN_PLAN_REVIEW_REQUIRED: 3,
    RUN_PLAN_REVISING: 4,
    RUN_PLAN_APPROVED: 5,
    RUN_WORKING: 6,
    RUN_WORK_DONE: 7,
    RUN_REVIEWING: 8,
    RUN_NEEDS_CHANGES: 9,
    RUN_REVIEW_RETRYABLE: 9,
    RUN_APPROVED: 10,
    RUN_BLOCKED: 10,
    RUN_FAILED: 10,
}
